<form class="form-horizontal">
  <fieldset>
    <legend>Send email to us</legend>
    <div class="form-group">
      <label for="inputEmail" class="col-lg-2 control-label">Email</label>
      <div class="col-lg-10">
        <input type="text" class="form-control" id="inputEmail" placeholder="Email">
      </div>
    </div>
    <div class="form-group">
      <label for="textArea" class="col-lg-2 control-label">Textarea</label>
      <div class="col-lg-10">
        <textarea class="form-control" rows="3" id="textArea"></textarea>
        <span class="help-block">You can ask us about what you need don't be shy , just ask!</span>
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <button type="submit" class="btn btn-primary">Send</button>
        <button type="reset" class="btn btn-default">Cancel</button>
      </div>
    </div>
  </fieldset>
</form>


<fieldset id="gmap">
    <div id="gmapdiv">
    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d42324.94702113984!2d34.96876158791675!3d48.46978271342891!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sru!2sru!4v1459444311749" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
</fieldset>